apiVersion: apps/v1
kind: Deployment
metadata:
  name: filter
  namespace: msa
  labels:
    app: filter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filter
  template:
    metadata:
      labels:
        app: filter
    spec:
      containers:
      - name: filter
        image: siokim002/sinbi_filter:15
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "700Mi"
