apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtualaccount
  namespace: msa
  labels:
    app: virtualaccount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtualaccount
  template:
    metadata:
      labels:
        app: virtualaccount
    spec:
      containers:
      - name: virtualaccount
        image: siokim002/sinbi_virtual_account:latest   # 이미지로 변경
        ports:
        - containerPort: 8082
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "700Mi"
